### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by sclipman** [vbsreenu/Tanoti#1]
Hi Sreenu,

I'm trying to use Tanoti on a Mac running MacOS 11.5.2 with an Intel Core i7 CPU and am getting a `Bad CPU` and `awk` error below. Do you have any suggestions for remedying this?

Thank you!

Executed using: `tanoti -r HIV_ref.fasta -i test_sample_1.fq.gz test_sample_2.fq.gz -o test.sam -p 1`

Error displays:
```
=====
/usr/local/bin/tanoti: line 210: /usr/local/bin/tan_fmdb: Bad CPU type in executable

Preprocessing...
awk: can't open file tnt_0_84546
 source line number 1
/usr/local/bin/tanoti: line 253: ((: i <= : syntax error: operand expected (error token is " ")
Generating a SAM file...
cat: tnt_8_*: No such file or directory
Time taken 0:0
Removing temporary files....
```

**Comment by sclipman** [comment]
**Update:** I recompiled the binaries to fix the `Bad CPU` error, but I'm still getting the error below, despite altering permissions (`chmod +x`). If you have any suggestions, please let me know!

```
=====
/usr/local/bin/tanoti: line 211: /usr/local/bin/formatdb: cannot execute binary file

Preprocessing...
awk: can't open file tnt_0_15434
 source line number 1
/usr/local/bin/tanoti: line 254: ((: i <= : syntax error: operand expected (error token is " ")
Generating a SAM file...
cat: tnt_8_*: No such file or directory
```

**Comment by awesel** [comment]
I am also having this problem. What was the solution?

**Comment by sclipman** [comment]
If I remember correctly, I recompiled the code on MacOS or ran it in a Linux image.

**Comment by awesel** [comment]
Thank you for these ideas! It ended up being an issue with security permissions for me, I had to verify the developer so that the pre/post processors could run.
